version: '3.0'
services:
  postgres:
    container_name: 'postgres'
    image: 'postgres:14.2-alpine'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: esdp3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes: 
      - ~/pgdata:/var/lib/postgresql/data
  backend:
    image: ${IMAGE_APP_TAG}
    ports:
      - "3000:3000" 
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ~/static:/public
      # - добавить логи

